import Head from 'next/head';
import Map from '../components/Map';
import Layout from '../components/Layout';
import React from 'react';
import Header from '../components/Header';
import Services from '../components/Services';
import Content from '../components/Content';
import ParallaxImage from '../components/ParallaxImage';
import Heading from '../components/Heading';
import History from '../components/History';
import Partners from '../components/Partners';
import About from '../components/About';
import Gallery from '../components/Gallery';
import Anchor from '../components/Anchor';
import Pension from '../components/Pension';
import { useLocales } from './api/useLocales';
import TrailRiding from '../components/TrailRiding';
import AboutMore from '../components/AboutMore';
import { FacebookIcon } from '../components/FacebookIcon';

const Spacer = () => <div className="py-4 md:py-6"></div>;
const Divider = () => <div className={`border-b-2 border-gray-100 py-2 md:py-6`} />;
const Centered = ({ children }) => <div className="flex flex-col md:items-center">{children}</div>;
const Slim = ({ children }) => <div className="max-w-lg">{children}</div>;

export default function Home() {
  const [fr, de] = useLocales();
  return (
    <Layout>
      <Head>
        <title>Les Écuries du Flecken</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {/* <Header small /> */}
      <Content>
        {/* <div className="fixed right-2 bottom-2 sm:right-6 sm:bottom-6 bg-white hover:bg-gray-300 rounded-full z-10">
          <a
            href="https://www.facebook.com/Les-Ecuries-du-Flecken-107285571760209"
            className="text-base text-gray-300"
            target="_blank"
            rel="noreferrer"
          >
            <FacebookIcon className="h-12 w-12 text-facebook" aria-hidden="true" />
          </a>
        </div> */}
        <Spacer />
        <Centered>
          <Heading>
            {de && 'Willkommen auf unserem Hof'}
            {fr && 'Bienvenue dans nos écuries'}
          </Heading>
          <About />
        </Centered>
        <Divider />
        <Spacer />
        <Services />
        <Divider />
        <Spacer />
        <Centered>
          <Anchor id="hof" />
          <Heading>
            {de && 'Unser Hof'}
            {fr && 'Nos Installations'}
          </Heading>
          {/* <Slim>
            = Galerie
            <br />
            <ul>
              <li>Manège éclairé avec barres, chandeliers, plots, …</li>
              <li>Paddocks</li>
              <li>Douche et aire de pansage</li>
              <li>Structure labellisée Tourisme Equestre</li>
              <li>Plusieurs hectares de pâtures vallonées et clôturées (3 fils électrifiés sur secteur)</li>
              <li>Foin de qualité supérieure entièrement produit sur la ferme</li>
              <li>Structure sous vidéosurveillance et présence 24h/24</li>
              <li>
                Ecuries ouvertes, protégées du vent, mais avec une bonne circulation de l’air (moins de poussière)
              </li>
            </ul>
          </Slim> */}
        </Centered>
        <Spacer />
        <Gallery />
        <Divider />
        <Spacer />
        {/* <Centered>
          <Heading>Historie</Heading>
          <Slim>
            <History />
          </Slim>
        </Centered>
        <Divider />
        <Spacer /> */}

        <TrailRiding />
        <Divider />
        <Spacer />

        <Pension />
        <Divider />
        <Spacer />

        <AboutMore />
        <Divider />
        <Spacer />

        <Centered>
          <Heading>
            {de && 'Anfahrt'}
            {fr && <>Plan d&apos;accès</>}
          </Heading>
          {/* <Slim>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.</p>
          </Slim> */}
        </Centered>
        <Spacer />
        <Map />
        <Divider />
        <Spacer />
        <Centered>
          <Heading>
            {de && 'Partner'}
            {fr && 'Nos Partenaires'}
          </Heading>
        </Centered>
        <Partners />
        <Divider />
        <ParallaxImage src="./img/mampfen.jpg.webp" />
      </Content>
    </Layout>
  );
}
