import Head from 'next/head';
import Map from '../components/Map';
import Layout from '../components/Layout';
import React from 'react';
import Header from '../components/Header';
import Services from '../components/Services';
import Content from '../components/Content';
import ParallaxImage from '../components/ParallaxImage';
import Heading from '../components/Heading';
import Contact from '../components/Contact';
import History from '../components/History';
import Partners from '../components/Partners';
import MediaLeft from '../components/MediaLeft';
import About from '../components/About';
import Gallery from '../components/Gallery';

const Spacer = () => <div className="mb-4"></div>;
const Section = ({ children, className, style }: any) => (
  <section className={`text-center py-6 ${className}`} style={style}>
    {children}
  </section>
);
const Divider = () => <div className={`border-b-2 border-gray-100 py-6`} />;

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Les Ecuries du Flecken</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {/* <Header small /> */}
      <Content>
        <Spacer />
        <Section>
          <Heading>Über Uns</Heading>
          <About />
        </Section>
        <Divider />
        <Spacer />
        <Services />
        <Divider />
        <Spacer />
        {/* <Section>
          <Heading>Über Uns</Heading>
          <About />
        </Section> */}
        <Section>
          <Heading>Historie</Heading>
          <div className="flex justify-center">
            <div className="max-w-lg mb-6">
              <History />
            </div>
          </div>
        </Section>
        <Divider />
        <Section>
          <Heading>Unser Hof</Heading>
          <Gallery />
        </Section>
        <Divider />
        <Section>
          <Heading>Urlaub machen</Heading>
        </Section>
        <Divider />
        <Section>
          <Heading>Elevage</Heading>
        </Section>
        <Divider />
        <ParallaxImage src="./img/mampfen.jpg" />
        <Spacer />
        <Section>
          <div className="text-center">
            <Heading>Partner</Heading>
          </div>
          <Partners />
        </Section>
        <Divider />
      </Content>
      <div className="text-center mt-6">
        <Heading>Anfahrt</Heading>
      </div>
      <Map />
    </Layout>
  );
}
