import Head from 'next/head';
import Map from '../components/Map';
import Layout from '../components/Layout';
import React from 'react';
import Header from '../components/Header';
import Services from '../components/Services';
import Content from '../components/Content';
import ParallaxImage from '../components/ParallaxImage';
import Heading from '../components/Heading';
import History from '../components/History';
import Partners from '../components/Partners';
import About from '../components/About';
import Gallery from '../components/Gallery';
import Anchor from '../components/Anchor';
import Pension from '../components/Pension';
import { useLocale } from './api/useLocales';

const Spacer = () => <div className="py-4 md:py-6"></div>;
const Divider = () => <div className={`border-b-2 border-gray-100 py-2 md:py-6`} />;
const Centered = ({ children }) => <div className="flex flex-col md:items-center">{children}</div>;
const Slim = ({ children }) => <div className="max-w-lg">{children}</div>;

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Les Ecuries du Flecken</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {/* <Header small /> */}
      <Content>
        <Spacer />
        <Centered>
          <Heading>Présentation / Über uns</Heading>
          <About />
        </Centered>
        <Divider />
        <Spacer />
        <Services />
        <Divider />
        <Spacer />
        <Centered>
          <Anchor id="hof" />
          <Heading>Unser Hof</Heading>
          <Slim>
            = Galerie
            <br />
            <ul>
              <li>Manège éclairé avec barres, chandeliers, plots, …</li>
              <li>Paddocks</li>
              <li>Douche et aire de pansage</li>
              <li>Structure labellisée Tourisme Equestre</li>
              <li>Plusieurs hectares de pâtures vallonées et clôturées (3 fils électrifiés sur secteur)</li>
              <li>Foin de qualité supérieure entièrement produit sur la ferme</li>
              <li>Structure sous vidéosurveillance et présence 24h/24</li>
              <li>
                Ecuries ouvertes, protégées du vent, mais avec une bonne circulation de l’air (moins de poussière)
              </li>
            </ul>
          </Slim>
        </Centered>
        <Spacer />
        <Gallery />
        <Divider />
        <Spacer />
        <Centered>
          <Heading>Historie</Heading>
          <Slim>
            <History />
          </Slim>
        </Centered>
        <Divider />
        <Spacer />

        <Pension />
        <Divider />
        <Spacer />

        <Centered>
          <Heading>Anfahrt</Heading>
          <Slim>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.</p>
          </Slim>
        </Centered>
        <Spacer />
        <Map />
        {/* <Divider />
        <Spacer />
        <Centered>
          <Heading>Urlaub machen</Heading>
        </Centered>
        <Divider />
        <Centered>
          <Heading>Elevage</Heading>
        </Centered> */}
        <Divider />
        <Spacer />
        <Centered>
          <Heading>Partner</Heading>
        </Centered>
        <Partners />
        <Divider />
        <ParallaxImage src="./img/mampfen.jpg" />
      </Content>
    </Layout>
  );
}
